### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SoulMateWF** [simonefinelli/ASL-Real-time-Recognition#1]
PS C:\MyProject\ASL-Real-time-Recognition-main> python train_model.py
Traceback (most recent call last):
  File "train_model.py", line 28, in <module>
    labels = labels_to_number(TRAIN_PATH)
  File "C:\MyProject\ASL-Real-time-Recognition-main\data_utils.py", line 12, in labels_to_number
    classes = [i.split(os.path.sep)[3] for i in glob.glob(path + '*')]
  File "C:\MyProject\ASL-Real-time-Recognition-main\data_utils.py", line 12, in <listcomp>
    classes = [i.split(os.path.sep)[3] for i in glob.glob(path + '*')]
IndexError: list index out of range

**Comment by simonefinelli** [comment]
SoulMateWF only now I have seen the open problem, so I apologize for the late reply.

Anyway, I took a look at the problem and in my opinion it could be due to a path problem. I see that you are working under Windows, unfortunately the code was developed and tested in a Linux environment.

You can try to copy the whole project to google drive and use Google Colab to run the tests.

Let me know if you have any further problems.
